# Use the official Python base image
FROM python

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script to the working directory
COPY rng.py .

# Install any necessary dependencies
# RUN pip install <dependency>

# Set the command to run the Python script
CMD ["python", "rng.py"]